version: "3.1"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    volumes:
      - meilisearch:/footwear_shop/meili_data
    ports:
      - 7701:7700
  postgres:
    image: postgres:latest
    container_name: footwear_shop_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-footwear_shop}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Admin@123}
      - POSTGRES_DB=${POSTGRES_DB:-footwear_shop_database}
    volumes:
      - postgres_data:/var/lib/postgresql/footwear_shop_database/data
    ports:
      - "5455:5432"
    restart: always
  # redis:
  #   image: 'bitnami/redis:latest'
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - "6379:6379"
volumes:
  meilisearch:
  postgres_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
